### ISSUE TITLE
screen cast link no longer works.

### ISSUE THREAD

**Issue by ryantig** [cloudnull/InstanceSync#14]
README.rst points to a screen cast of a migration [http://ascii.io/a/1063] - this link is no longer valid. Is there a good link/home for the video (or a newer rev?) Thanks

**Comment by cloudnull** [comment]
Looks like a domain change is no longer redirecting. PR inbound. Thanks for noticing.

**Comment by cloudnull** [comment]
This is the new link https://asciinema.org/a/1063

**Comment by ryantig** [comment]
Thanks for the code + demo + update. :)
